version: '3'
services:
    postgres:
        container_name: postgres15
        image: postgres:15.2
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5432:5432"
    meu-backend:
        container_name: alpinejdk17
        image: openjdk:17-jdk-alpine3.14
        ports:
            - "8080:8080"
